dist: xenial

services:
  - elasticsearch

language: python

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py36-elastic6 ES_APT_URL=https://artifacts.elastic.co/packages/6.x/apt
    python: 3.6
  - env: TOX_ENV=py36-elastic7
    python: 3.6

  - env: TOX_ENV=py37-elastic6 ES_APT_URL=https://artifacts.elastic.co/packages/6.x/apt ALLOW_FAILURE=true
    python: 3.7
  - env: TOX_ENV=py37-elastic7 ALLOW_FAILURE=true
    python: 3.7

  - env: TOX_ENV=py38-elastic6 ES_APT_URL=https://artifacts.elastic.co/packages/6.x/apt
    python: 3.8
  - env: TOX_ENV=py38-elastic7
    python: 3.8
  allow_failures:
    - env: ALLOW_FAILURE=true

env:
  global:
    - ES_APT_URL=https://artifacts.elastic.co/packages/7.x/apt

before_install:
#  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.1.1-amd64.deb && sudo service elasticsearch restart
#  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.5.4.deb && sudo service elasticsearch restart
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb $ES_APT_URL stable main" | sudo tee -a /etc/apt/sources.list.d/elk.list
  - sudo apt-get remove --purge elasticsearch -y
  - sudo apt-get update && sudo apt-get install elasticsearch -y
  - sudo -i service elasticsearch restart

install: pip install -r requirements/test.txt

before_script:
  # sleep for elasticsearch
  - wget -q --waitretry=3 --retry-connrefused -T 10 -O - http://127.0.0.1:9200

script: travis_retry tox -e $TOX_ENV

after_success:
  - pip install coveralls
  - coveralls
