dist: xenial

services:
  - elasticsearch

language: python

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py36-elastic7
    python: 3.6
  - env: TOX_ENV=py37-elastic7
    python: 3.7

before_install:
#  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.1.1-amd64.deb && sudo service elasticsearch restart
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.5.4.deb && sudo service elasticsearch restart

install: pip install -r requirements/testing.txt

before_script:
  # sleep for elasticsearch
  - wget -q --waitretry=3 --retry-connrefused -T 10 -O - http://127.0.0.1:9200

script: travis_retry tox -e $TOX_ENV
